#! /usr/bin/expect

set IP   [lindex $argv 0]
#spawn scp -i id_rsa_oci6 -oStrictHostKeyChecking=no opc@$IP:/home/opc/ipaddr2 .
spawn scp -i id_rsa_oci6 opc@$IP:/home/opc/ipaddr2 .
expect "(yes/no)?"
#send "yes\n"
#expect "~]$"
#send "\r\n"
exit
