#! /usr/bin/bash

nslookup fileserverad >> fileserverad1
sed -i '/^$/d' fileserverad1
sed '/^$/!h;$!d;g' fileserverad1 | egrep -o "([0-9]{1,3}.){3}[0-9]" >> ipaddr
echo "  fileserverad1.subnetad1.clustervcn.oraclevcn.com fileserverad1" >> ipaddr
cat ipaddr | tr "\n" " " >> ipaddr2
